// Course catalogue used for recommendations.
//
// IMPORTANT: `igotUrl` values below are PLACEHOLDER links in the correct iGOT
// Karmayogi URL shape (https://portal.igotkarmayogi.gov.in/app/toc/do_<id>/overview)
// but the `do_...` content IDs are NOT real course IDs — this server has no live
// access to iGOT's catalogue. Before a real demo/production use, replace each
// igotUrl with the actual course URL copied from iGOT (open the course on iGOT,
// copy the address-bar URL). Everything else (matching, scoring, recommendation
// logic) works the same regardless of which URLs are plugged in here.

const courses = [
  { id: 'py-data-analysis', title: 'Python for Data Analysis', duration: '12 hours', provider: 'iGOT Karmayogi', skillTags: ['Python', 'Data quality'], description: 'Build reliable analysis workflows with tabular official-statistics data.', igotUrl: 'https://portal.igotkarmayogi.gov.in/app/toc/do_placeholder_python_analysis/overview' },
  { id: 'sql-gov-analytics', title: 'SQL for Government Data Analytics', duration: '10 hours', provider: 'iGOT Karmayogi', skillTags: ['SQL', 'Digital systems'], description: 'Query, join and validate large administrative and survey datasets.', igotUrl: 'https://portal.igotkarmayogi.gov.in/app/toc/do_placeholder_sql_gov/overview' },
  { id: 'r-statistical-analysis', title: 'R for Statistical Analysis', duration: '9 hours', provider: 'iGOT Karmayogi', skillTags: ['R', 'Statistical foundations'], description: 'Use R for reproducible statistical analysis and reporting.', igotUrl: 'https://portal.igotkarmayogi.gov.in/app/toc/do_placeholder_r_stats/overview' },
  { id: 'excel-official-stats', title: 'Excel for Official Statistics', duration: '6 hours', provider: 'iGOT Karmayogi', skillTags: ['Excel', 'Data quality'], description: 'PivotTables, validation and clean data entry for statistical work.', igotUrl: 'https://portal.igotkarmayogi.gov.in/app/toc/do_placeholder_excel_stats/overview' },
  { id: 'dataviz-decisions', title: 'Data Visualisation for Decisions', duration: '8 hours', provider: 'iGOT Karmayogi', skillTags: ['Data visualization', 'Data communication'], description: 'Turn statistical results into clear decision-ready dashboards.', igotUrl: 'https://portal.igotkarmayogi.gov.in/app/toc/do_placeholder_dataviz/overview' },
  { id: 'ml-public-data', title: 'Machine Learning Foundations for Public Data', duration: '14 hours', provider: 'iGOT Karmayogi', skillTags: ['Machine learning', 'Digital systems'], description: 'Core ML concepts, applied carefully to government datasets.', igotUrl: 'https://portal.igotkarmayogi.gov.in/app/toc/do_placeholder_ml_public/overview' },
  { id: 'stats-foundations-refresher', title: 'Statistical Foundations Refresher', duration: '7 hours', provider: 'iGOT Karmayogi', skillTags: ['Statistical foundations', 'Applied statistics'], description: 'Sampling, central tendency, bias and confidence — the essentials.', igotUrl: 'https://portal.igotkarmayogi.gov.in/app/toc/do_placeholder_stats_refresher/overview' },
  { id: 'data-quality-validation', title: 'Data Quality & Validation Essentials', duration: '6 hours', provider: 'iGOT Karmayogi', skillTags: ['Data quality', 'Data validation'], description: 'Practical checks for completeness, uniqueness and plausibility.', igotUrl: 'https://portal.igotkarmayogi.gov.in/app/toc/do_placeholder_data_quality/overview' },
  { id: 'data-governance-privacy', title: 'Data Governance & Privacy in Government', duration: '8 hours', provider: 'iGOT Karmayogi', skillTags: ['Data governance', 'Digital governance'], description: 'Handling personal and sensitive data responsibly in official systems.', igotUrl: 'https://portal.igotkarmayogi.gov.in/app/toc/do_placeholder_data_governance/overview' },
  { id: 'cyber-digital-governance', title: 'Cybersecurity & Digital Governance Basics', duration: '5 hours', provider: 'iGOT Karmayogi', skillTags: ['Digital governance', 'Data validation'], description: 'Recognising and responding to common digital-security risks.', igotUrl: 'https://portal.igotkarmayogi.gov.in/app/toc/do_placeholder_cyber_basics/overview' },
  { id: 'metadata-reproducible-practice', title: 'Metadata & Reproducible Data Practice', duration: '6 hours', provider: 'iGOT Karmayogi', skillTags: ['Data practice', 'Data dissemination'], description: 'Documenting data and building auditable, versioned workflows.', igotUrl: 'https://portal.igotkarmayogi.gov.in/app/toc/do_placeholder_metadata_practice/overview' },
  { id: 'dashboard-mis-development', title: 'Dashboard & MIS Development', duration: '9 hours', provider: 'iGOT Karmayogi', skillTags: ['Dashboard / MIS', 'Data visualization'], description: 'Designing monitoring dashboards that highlight decision-relevant KPIs.', igotUrl: 'https://portal.igotkarmayogi.gov.in/app/toc/do_placeholder_dashboard_mis/overview' },
  { id: 'plfs-deep-dive', title: 'Labour Force Statistics: PLFS Deep Dive', duration: '10 hours', provider: 'iGOT Karmayogi', skillTags: ['PLFS', 'Labour statistics'], description: 'Employment status, WPR and labour-force survey methodology.', igotUrl: 'https://portal.igotkarmayogi.gov.in/app/toc/do_placeholder_plfs/overview' },
  { id: 'cpi-economic-stats', title: 'Consumer Price Index & Economic Statistics', duration: '8 hours', provider: 'iGOT Karmayogi', skillTags: ['CPI', 'Economic statistics'], description: 'Index construction, base years and real-value adjustment.', igotUrl: 'https://portal.igotkarmayogi.gov.in/app/toc/do_placeholder_cpi/overview' },
  { id: 'asi-industrial-stats', title: 'Industrial Statistics: ASI Essentials', duration: '7 hours', provider: 'iGOT Karmayogi', skillTags: ['ASI', 'Economic statistics'], description: 'Factory-sector data collection and gross value added.', igotUrl: 'https://portal.igotkarmayogi.gov.in/app/toc/do_placeholder_asi/overview' },
  { id: 'hces-demography', title: 'Household Consumption & Demography', duration: '8 hours', provider: 'iGOT Karmayogi', skillTags: ['HCES', 'Demography', 'Demographic statistics'], description: 'Consumption survey design and demographic rate construction.', igotUrl: 'https://portal.igotkarmayogi.gov.in/app/toc/do_placeholder_hces_demo/overview' },
  { id: 'national-accounts-gdp', title: 'National Accounts & GDP Estimation', duration: '10 hours', provider: 'iGOT Karmayogi', skillTags: ['National Accounts', 'Economic statistics'], description: 'How GDP and real output are estimated and interpreted.', igotUrl: 'https://portal.igotkarmayogi.gov.in/app/toc/do_placeholder_national_accounts/overview' },
  { id: 'communicating-data', title: 'Communicating Data to Decision-Makers', duration: '5 hours', provider: 'iGOT Karmayogi', skillTags: ['Data communication'], description: 'Framing statistical findings clearly for non-technical audiences.', igotUrl: 'https://portal.igotkarmayogi.gov.in/app/toc/do_placeholder_communicating_data/overview' }
];

module.exports = { courses };
